// file automatically generated by angular-template-cache

import angular from 'angular';

const templatesModule = angular
	.module('templates', [])
	.run(['$templateCache', function($templateCache) {
		$templateCache.put('components/breadcrumbs/breadcrumbs.tpl.html', '<nav aria-label="breadcrumb">\n' +
			'  <ol class="mt-3 mb-4 bg-secondary breadcrumb breadcrumb-border">\n' +
			'    <li ng-repeat="crumb in breadcrumbs" ng-class="[\'breadcrumb-item\', { active: $last }]" aria-current="{{!$last || \'page\'}}">\n' +
			'      <a ng-if="!$last" ng-href="{{ crumb.href }}">{{ crumb.displayName }}</a>\n' +
			'      <span ng-show="$last">{{ crumb.displayName }}</span>\n' +
			'    </li>\n' +
			'  </ol>\n' +
			'</nav>');

		$templateCache.put('components/footer/footer.tpl.html', '<footer class="ctp-footer" ng-click="footerClick()">\n' +
			'  <div class="container mt-5">\n' +
			'    <div class="row mb-3 pt-5">      \n' +
			'      <div class="col-lg-2">\n' +
			'        <h5 class="ctp-footer__heading">Testing 1</h5>\n' +
			'        <ul class="ctp-footer__links list-links list-unstyled">\n' +
			'          <li><a target="_blank" href="">Test1</a></li>\n' +
			'          <li><a target="_blank" href="">Test1</a></li>\n' +
			'          <li><a target="_blank" href="">Test1</a></li>\n' +
			'          <li><a target="_blank" href="">Test1</a></li>\n' +
			'          <li><a target="_blank" href="">Test1</a></li>\n' +
			'          <li><a target="_blank" href="">Test1</a></li>\n' +
			'          <li><a target="_blank" href="">Test1</a></li>\n' +
			'        </ul>\n' +
			'      </div>\n' +
			'\n' +
			'      <div class="col-lg-2">\n' +
			'        <h5 class="ctp-footer__heading">More testing</h5>\n' +
			'        <ul class="ctp-footer__links list-links list-unstyled">\n' +
			'          <li><a target="_blank" href="">Test2</a></li>\n' +
			'          <li><a target="_blank" href="">Test2</a></li>\n' +
			'          <li><a target="_blank" href="">Test2</a></li>\n' +
			'          <li><a target="_blank" href="">Test2</a></li>\n' +
			'          <li><a target="_blank" href="">Test2</a></li>\n' +
			'          <li><a target="_blank" href="">Test2</a></li>\n' +
			'          <li><a target="_blank" href="">Test2</a></li>\n' +
			'        </ul>\n' +
			'      </div>\n' +
			'    </div>\n' +
			'  </div>\n' +
			'</footer>');

		$templateCache.put('components/search-box/search-box.tpl.html', '<form class="d-flex justify-content-start">\n' +
			'  <input class="form-control pr-4" type="text" ng-model="value" name="searchInput" placeholder="Search for item" autocomplete="off">\n' +
			'  <button class="btn border-0 px-1" ng-click="onSearchAction()" style="margin-left: -25px; background: transparent;">\n' +
			'    <i class="fas fa-search"></i>\n' +
			'  </button>\n' +
			'</form>');

		$templateCache.put('index.html', '<!DOCTYPE html>\n' +
			'<html>\n' +
			'  <head lang="en">\n' +
			'    <meta charset="utf-8">\n' +
			'    <meta http-equiv="X-UA-Compatible" content="IE=edge">\n' +
			'    <title><%= htmlWebpackPlugin.options.title %></title>\n' +
			'  </head>\n' +
			'  <body ng-app="app">\n' +
			'\n' +
			'    \n' +
			'    <!-- Router Templates Render Here  -->\n' +
			'    <div class="container">\n' +
			'      <breadcrumbs breadcrumb-list="[{\'displayName\':\'Test 1\',\'href\':\'https://google.com/\'},{\'displayName\':\'Test 2\',\'href\':\'https://google.com/\'}]"></breadcrumbs>\n' +
			'      <search-box></search-box>\n' +
			'      <h2>Footer below</h2>\n' +
			'      <ctp-ecom-footer></ctp-ecom-footer>\n' +
			'    </div>\n' +
			'</body></html>');
	}
]);

export default templatesModule;
